In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df_original = pd.read_csv("data.csv", encoding="latin-1")

In [3]:
df_copy = df_original.copy()

In [4]:
df_copy.shape

(541909, 8)

In [5]:
df_copy.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
df_copy.duplicated().sum()

np.int64(5268)

In [7]:
df_copy.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [9]:
df_copy=df_copy.dropna(subset=["CustomerID"])

In [10]:
#Since customerID is in float, it is bette to change in integer, 
df_copy.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [11]:
df_copy['CustomerID'] = df_copy['CustomerID'].astype('int64')

In [12]:
df_copy.shape

(406829, 8)

In [13]:
df_copy.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID       int64
Country            str
dtype: object

In [14]:
df_copy.duplicated().sum()

np.int64(5225)

In [15]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  str
 1   StockCode    406829 non-null  str
 2   Description  406829 non-null  str
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  str
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  int64
 7   Country      406829 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 27.9 MB

In [16]:
df_copy['CustomerID'].duplicated().sum()

np.int64(402457)

In [17]:
df_copy['CustomerID'].nunique()

4372

In [18]:
df_copy.describe()

            Quantity      UnitPrice     CustomerID
count  406829.000000  406829.000000  406829.000000
mean       12.061303       3.460471   15287.690570
std       248.693370      69.315162    1713.600303
min    -80995.000000       0.000000   12346.000000
25%         2.000000       1.250000   13953.000000
50%         5.000000       1.950000   15152.000000
75%        12.000000       3.750000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [19]:
df_copy['StockCode'].duplicated().sum()

np.int64(403145)

In [20]:
df_copy['Country'].duplicated().sum()

np.int64(406792)

In [21]:
df_copy['InvoiceDate'].duplicated().sum()

np.int64(386369)

In [22]:
df_copy['InvoiceDate'] =pd.to_datetime(df_copy['InvoiceDate'])

In [23]:
df_copy.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              int64
Country                   str
dtype: object

In [24]:
df_copy['Total Price'] = df_copy['Quantity'] * df_copy['UnitPrice']

In [25]:
df_copy.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total Price
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85

In [26]:
df_copy['Year_Month'] = df_copy['InvoiceDate'].dt.strftime('%B %Y')
df_copy['Day_Time'] = df_copy['InvoiceDate'].dt.strftime('%d %H:%M:%S')

In [27]:
df_copy.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00

In [28]:
df_copy.drop(columns=['InvoiceDate'], inplace=True)

In [29]:
df_copy.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00

In [30]:
df_copy['Description'] = df_copy['Description'].str.strip().str.lower()

In [31]:
df_copy.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,white hanging heart t-light holder,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,white metal lantern,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,cream cupid hearts coat hanger,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,knitted union flag hot water bottle,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,red woolly hottie white heart.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00

In [32]:
df_copy.shape

(406829, 10)

In [33]:
df_copy["Quantity"].describe()

count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [34]:
df_copy.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
UnitPrice      0
CustomerID     0
Country        0
Total Price    0
Year_Month     0
Day_Time       0
dtype: int64

In [35]:
df_copy.shape

(406829, 10)

In [36]:
df_copy = df_copy[df_copy['Quantity'] > 0]

In [37]:
df_copy

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,white hanging heart t-light holder,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,white metal lantern,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,cream cupid hearts coat hanger,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,knitted union flag hot water bottle,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,red woolly hottie white heart.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,pack of 20 spaceboy napkins,12,0.85,12680,France,10.20,December 2011,09 12:50:00
541905,581587,22899,children's apron dolly girl,6,2.10,12680,France,12.60,December 2011,09 12:50:00
541906,581587,23254,childrens cutlery dolly girl,4,4.15,12680,France,16.60,December 2011,09 12:50:00
541907,581587,23255,childrens cutlery circus parade,4,4.15,12680,France,16.60,December 2011,09 12:50:00
541908,581587,22138,baking set 9 piece retrospot,3,4.95,12680,France,14.85,December 2011,09 12:50:00

In [38]:
df_copy = df_copy[df_copy['UnitPrice'] > 0]

In [39]:
df_copy

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,white hanging heart t-light holder,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,white metal lantern,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,cream cupid hearts coat hanger,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,knitted union flag hot water bottle,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,red woolly hottie white heart.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,pack of 20 spaceboy napkins,12,0.85,12680,France,10.20,December 2011,09 12:50:00
541905,581587,22899,children's apron dolly girl,6,2.10,12680,France,12.60,December 2011,09 12:50:00
541906,581587,23254,childrens cutlery dolly girl,4,4.15,12680,France,16.60,December 2011,09 12:50:00
541907,581587,23255,childrens cutlery circus parade,4,4.15,12680,France,16.60,December 2011,09 12:50:00
541908,581587,22138,baking set 9 piece retrospot,3,4.95,12680,France,14.85,December 2011,09 12:50:00

In [40]:
df_copy['Quantity'].min()

np.int64(1)

In [41]:
df_copy['UnitPrice'].min()

np.float64(0.001)

In [42]:
df_copy.reset_index(drop=True, inplace= True)

In [43]:
df_copy

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,white hanging heart t-light holder,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,white metal lantern,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,cream cupid hearts coat hanger,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,knitted union flag hot water bottle,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,red woolly hottie white heart.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
...,...,...,...,...,...,...,...,...,...,...
397879,581587,22613,pack of 20 spaceboy napkins,12,0.85,12680,France,10.20,December 2011,09 12:50:00
397880,581587,22899,children's apron dolly girl,6,2.10,12680,France,12.60,December 2011,09 12:50:00
397881,581587,23254,childrens cutlery dolly girl,4,4.15,12680,France,16.60,December 2011,09 12:50:00
397882,581587,23255,childrens cutlery circus parade,4,4.15,12680,France,16.60,December 2011,09 12:50:00
397883,581587,22138,baking set 9 piece retrospot,3,4.95,12680,France,14.85,December 2011,09 12:50:00

In [44]:
print(df_copy.isnull().sum())

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
UnitPrice      0
CustomerID     0
Country        0
Total Price    0
Year_Month     0
Day_Time       0
dtype: int64

In [45]:
df_copy['StockCode'].value_counts().tail(40)

StockCode
90038A    1
84016     1
23630     1
90059A    1
20678     1
90059D    1
90168     1
90169     1
90202A    1
90118     1
90177A    1
90177E    1
90182C    1
90028     1
90074     1
90129E    1
90054     1
90071     1
90025F    1
47016     1
90181A    1
90199B    1
90069     1
90176A    1
90176B    1
90162A    1
90065B    1
23664     1
23449     1
84206B    1
22125     1
90130A    1
90011A    1
84550     1
90214O    1
90214T    1
90214U    1
90214W    1
90214Z    1
23843     1
Name: count, dtype: int64

In [46]:
df_copy['InvoiceNo'].shape

(397884,)

In [47]:
df_copy[df_copy['InvoiceNo'].str.startswith('C')]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID, Country, Total Price, Year_Month, Day_Time]
Index: []

In [48]:
df_copy['CustomerID'].nunique()

4338

In [49]:
df_copy= df_copy[df_copy['StockCode'] != 'invalid_code']

In [50]:
df_copy = df_copy[df_copy["Total Price"] > 0]
df_copy.shape

(397884, 10)

In [51]:
df_cleaned = df_copy.to_csv('cleaned_ecommerce.csv', index=False)

In [52]:
df_copy

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Total Price,Year_Month,Day_Time
0,536365,85123A,white hanging heart t-light holder,6,2.55,17850,United Kingdom,15.30,December 2010,01 08:26:00
1,536365,71053,white metal lantern,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
2,536365,84406B,cream cupid hearts coat hanger,8,2.75,17850,United Kingdom,22.00,December 2010,01 08:26:00
3,536365,84029G,knitted union flag hot water bottle,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
4,536365,84029E,red woolly hottie white heart.,6,3.39,17850,United Kingdom,20.34,December 2010,01 08:26:00
...,...,...,...,...,...,...,...,...,...,...
397879,581587,22613,pack of 20 spaceboy napkins,12,0.85,12680,France,10.20,December 2011,09 12:50:00
397880,581587,22899,children's apron dolly girl,6,2.10,12680,France,12.60,December 2011,09 12:50:00
397881,581587,23254,childrens cutlery dolly girl,4,4.15,12680,France,16.60,December 2011,09 12:50:00
397882,581587,23255,childrens cutlery circus parade,4,4.15,12680,France,16.60,December 2011,09 12:50:00
397883,581587,22138,baking set 9 piece retrospot,3,4.95,12680,France,14.85,December 2011,09 12:50:00

In [53]:
import pandas as pd

cleaned_ecommerce = pd.read_csv('cleaned_ecommerce.csv')

# Verify
print(cleaned_ecommerce.shape)
print(cleaned_ecommerce.head())

(397884, 10)
   InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   white hanging heart t-light holder         6
1     536365     71053                  white metal lantern         6
2     536365    84406B       cream cupid hearts coat hanger         8
3     536365    84029G  knitted union flag hot water bottle         6
4     536365    84029E       red woolly hottie white heart.         6

   UnitPrice  CustomerID         Country  Total Price     Year_Month  \
0       2.55       17850  United Kingdom        15.30  December 2010
1       3.39       17850  United Kingdom        20.34  December 2010
2       2.75       17850  United Kingdom        22.00  December 2010
3       3.39       17850  United Kingdom        20.34  December 2010
4       3.39       17850  United Kingdom        20.34  December 2010

      Day_Time
0  01 08:26:00
1  01 08:26:00
2  01 08:26:00
3  01 08:26:00
4  01 08:26:00

In [54]:
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

# URL.create() handles special characters in password safely
connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="@mami1515",       # @ symbol is now safe here
    host="localhost",
    port=5432,
    database="ecommerce"
)

try:
    engine = create_engine(connection_url)
    
    with engine.connect() as conn:
        print("✅ Connection successful!")
        
        tables = pd.read_sql_query(
            text("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public'
            """),
            conn
        )
        print(tables)

except Exception as e:
    print(f"❌ Connection failed: {e}")

✅ Connection successful!
  table_name
0  ecommerce

In [4]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# Step 1 - Load CSV
cleaned_ecommerce = pd.read_csv('cleaned_ecommerce.csv')
print("✅ CSV Loaded! Rows:", len(cleaned_ecommerce))
data = pd.read_csv('data.csv', encoding='latin1')
print("✅ CSV Loaded! Rows:", len(data))



# Step 2 - Connect to PostgreSQL
connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="@mami1515",
    host="localhost",
    port=5432,
    database="ecommerce"
)

engine = create_engine(connection_url)
print("✅ Connected to PostgreSQL!")

# Step 3 - Export to PostgreSQL
cleaned_ecommerce.to_sql(
    'ecommerce',          # table name in PostgreSQL
    engine,
    if_exists='replace',  # replace if table already exists
    index=False           # don't export dataframe index
)
data.to_sql(
    'original_data',
    engine,
    if_exists='replace',
    index = False
)


print("✅ Data exported successfully!")
print("Rows exported:", len(cleaned_ecommerce))

✅ CSV Loaded! Rows: 397884
✅ CSV Loaded! Rows: 541909
✅ Connected to PostgreSQL!
✅ Data exported successfully!
Rows exported: 397884